bot_folder: bot
llm_app_file_name: llm_app.py
benchmark_csv: benchmark_QA.csv
env_file_name: llm_env.env
mlflow_experiment_name: Default
evaluation_metrics:
  cosine_similarity: true
  ai_similarity: false
input_var: msg
experiment_vars:
internal_logged_vars:
  - intermediate_ans
  - prompt_template_1
  - prompt_template_2
chain_instruct:
  - fxn_name: test_two_prompt
    in:
      - msg
    out:
      - ans