llm_app_file_name: llm_app
benchmark_csv: benchmark_QA
env_file_name: llm_env
mlflow_experiment_name: Default
evaluation_metrics:
  cosine_similarity: true
  ai_similarity: false
input_var: raw_msg
experiment_vars:
internal_logged_vars:
  - retrieve_k
  - context
  - question_prompt_template
chain_instruct:
  - fxn_name: qna_llm
    in:
      - raw_msg
    out:
      - ans