bot_logic_file_name: bot_logic
benchmark_csv: benchmark_QA
env_file_name: llm_pgvector
mlflow_experiment_name: Default
mlflow_run_name: run 1
scoring:
  cosine_similarity: true
  ai_similarity: false # TODO:
constants:
  retrieve_k: 3
function_logging_vars:
  - engine
  - question_prompt_template
chain_instruct:
  createEmbeddings:
    in:
      - msg
    out:
      - questionEmbedding
  retrieve_k_chunk:
    in:
      - retrieve_k
      - questionEmbedding
    out:
      - top_rows
  get_context:
    in:
      - top_rows
    out:
      - context
  llm_call:
    in:
      - context
      - msg
    out:
      - ans